name: Run API Tests with Newman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Run API tests with Newman
        run: |
          newman run "https://raw.githubusercontent.com/VioletaMincheva/API-testing-project/refs/heads/main/Mini%20E-Commerce.json" 
            -e "https://raw.githubusercontent.com/VioletaMincheva/API-testing-project/refs/heads/main/Mock%20server%207.environment.json"
            --bail \
            --reporters cli,html,junit \
            --reporter-html-export newman-report.html \
            --reporter-junit-export newman-report.xml

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: newman-reports
          path: |
            newman-report.html
            newman-report.xml
